blacklist = ["scratch"]

dir_length = 2

[default_session]
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "Dotfiles"
startup_command = "chezmoi edit"
preview_command = "eza --all --git --icons --color=always ~/.local/share/chezmoi"
